"""Глобальные константы проекта."""

EMAIL_MAX_LENGTH = 254
USER_FIELD_MAX_LENGTH = 150

TAG_NAME_MAX_LENGTH = 32
TAG_SLUG_MAX_LENGTH = 32

INGREDIENT_NAME_MAX_LENGTH = 128
MEASUREMENT_UNIT_MAX_LENGTH = 64

RECIPE_NAME_MAX_LENGTH = 256

MIN_COOKING_TIME = 1
MIN_INGREDIENT_AMOUNT = 1

SHORT_CODE_LENGTH = 8
