# Generated by Django 6.1.1 on 2026-09-23 14:43
"""Миграция для создания модели Ingredient."""

from django.db import migrations, models


class Migration(migrations.Migration):
    """Класс миграции."""

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=128,
                        verbose_name="Название",
                    ),
                ),
                (
                    "measurement_unit",
                    models.CharField(
                        max_length=64,
                        verbose_name="Единица измерения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ингредиент",
                "verbose_name_plural": "Ингредиенты",
                "ordering": ("name",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "measurement_unit"),
                        name="unique_ingredient_measurement_unit",
                    )
                ],
            },
        ),
    ]
